/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.tevp.tubejourney;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int btnHome=0x7f050001;
        public static final int mainLayout=0x7f050000;
        public static final int textLog=0x7f050002;
    }
    public static final class layout {
        public static final int buttons=0x7f030000;
        public static final int log=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
